steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        docker run --rm -v /workspace:/workspace docker.io/zricethezav/gitleaks:v7.0.1 --path=/workspace --no-git --report=/workspace/gitleaks_result.csv
    id: scanning for leaks
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ -s "/workspace/gitleaks_result.csv" ]; then 
          echo "Leaks found!"; 
          awk -F'"' '/"file":/ {print}' /workspace/gitleaks_result.csv;
          exit 1; 
        else 
          echo "No leaks detected"; 
        fi
    id: secret leaks validation
options:
  logging: "CLOUD_LOGGING_ONLY"

